# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 521da645c4bbbf31a2fee57fd6bd1f6785b8f2682b1dc92c5d932436636d6522269c8703995913ba923a73b3d2433c3216a39ee1339cec9cf8d461b3ed3c3609

test:
  secret_key_base: 5491d980cd1832528535094d4156d51acbe56b35c548705a06a6afda46814537554cc10721ff846ed2ca13d2f9e04fd72a756c6afca712cfebfb679753d4a7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
